version: '3.9'
services:
  web:
    image: ruby
    working_dir: /app/app-medic
    volumes:
      - ./app-medic:/app/app-medic
      - labs-gems:/usr/local/bundle
    command: bash -c "bundle install && ruby server.rb"
    environment: 
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
      - sidekiq
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./database:/var/lib/postgresql/data
  test:
    image: ruby
    working_dir: /app/app-medic
    volumes:
      - ./app-medic:/app/app-medic
      - labs-gems:/usr/local/bundle
    command: bash -c "bundle install && bundle exec rspec"
    environment:
      - RACK_ENV=test
    depends_on:
      - db-test
    networks:
      - tests
  db-test:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      tests:
        aliases:
          - db
  sidekiq:
    image: ruby
    working_dir: /app/app-medic
    volumes:
      - ./app-medic:/app/app-medic
      - labs-gems:/usr/local/bundle
    command: bash -c "bundle install && bundle exec sidekiq -r ./csv_importer.rb"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
  frontend:
    image: node
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: bash -c "npm install && npm run dev"
    ports:
      - "5500:5500"
    depends_on:
      - web
volumes:
  labs-gems:
networks:
  tests: