version: '3.9'
services:
  web:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    command: bash -c "cd app-medic/;bundle install && ruby server.rb"
    environment: 
      REDIS_URL: redis://redis:6379/0
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./database:/var/lib/postgresql/data
  sidekiq:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    command: bash -c "cd app-medic/;bundle exec sidekiq -r ./csv_importer.rb"
    environment:
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
volumes:
  labs-gems: