version: '3.9'
services:
  web:
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - labs-gems:/usr/local/bundle
    command: bash -c "bundle install && ruby server.rb"
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./database:/var/lib/postgresql/data
volumes:
  labs-gems: